### ISSUE TITLE
I'm a fucking dumbass  [improved title]

### ISSUE THREAD

**Issue by EnderNon** [GlowsAreLosers/GlowsAreLosers#2]
that's all i felt like opening an issue for 
please seek help

**Comment by ghost** [comment]
i am sorry to say. they is much validity in this text then you think.
or you are just a disinfo agent.

**Comment by notavailable852** [comment]
What link? I am missing it, can someone re post it here please?

**Comment by GlowsAreLosers** [comment]
You're a fucking moron if this is why you opened an issue for. Fuck off, and do not open issues again.
